baseURL = "/"
copyright = "CANFLY"
languageCode = "en-us"
theme = "Minimal"
title = "Canfly"
[[menu.icon]]
name = "fas fa-envelope"
url = "mailto:support@canfly.org"
weight = 1
[[menu.icon]]
name = "fab fa-github"
url = "https://github.com/Canfly/"
weight = 2
[[menu.icon]]
name = "fab fa-twitter"
url = "https://twitter.com/_canfly/"
weight = 3
[[menu.icon]]
name = "fab fa-whatsapp"
url = "https://wa.me/message/CK27C4PEWA3SD1"
weight = 4
[[menu.icon]]
name = "fab fa-facebook"
url = "https://www.facebook.com/canfly.org"
weight = 5
[[menu.icon]]
name = "fab fa-vk"
url = "https://vk.com/canfly_org"
weight = 6
[[menu.main]]
name = "Home"
url = "/"
weight = 1
[[menu.main]]
name = "About"
url = "/about/"
weight = 2
[params]
accent = "red"
author = "Adiom Timur"
backgroundColor = "white"
description = "We are looking for interesting teams and doing collaborations with them"
font = "Raleway"
githubUsername = "adiom"
highlight = true
highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]
highlightStyle = "default"
showBorder = true
